container_name       = "MYCONTAINER"
key                  = "prod.tfstate"
resource_group_name  = "estf"
storage_account_name = "MYSTORAGEACCOUNTNAME"
subscription_id      = "MYSUBSCRIPTIONID"
tenant_id            = "MYTENANTID"
